// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyButz4ql-2YlcgQ3r2HFajaZjGCKzyPFxc',
    appId: '1:880436784824:web:5050a14a98021989874e4d',
    messagingSenderId: '880436784824',
    projectId: 'tools-sharing-f91a6',
    authDomain: 'tools-sharing-f91a6.firebaseapp.com',
    storageBucket: 'tools-sharing-f91a6.appspot.com',
    measurementId: 'G-71NLFQJVY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-nbyG56-0OaQeaIEd2Gjn3P1qXGexCes',
    appId: '1:880436784824:android:6b46cf0315b17c6e874e4d',
    messagingSenderId: '880436784824',
    projectId: 'tools-sharing-f91a6',
    storageBucket: 'tools-sharing-f91a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgKaF-_uvNH9sYv6qzKEZOW4IBWfgmDJQ',
    appId: '1:880436784824:ios:63f666a978dd4d69874e4d',
    messagingSenderId: '880436784824',
    projectId: 'tools-sharing-f91a6',
    storageBucket: 'tools-sharing-f91a6.appspot.com',
    iosClientId: '880436784824-5ha35g91mr50k1pk3ugo0h4ud08d6s8q.apps.googleusercontent.com',
    iosBundleId: 'com.tools.sharing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgKaF-_uvNH9sYv6qzKEZOW4IBWfgmDJQ',
    appId: '1:880436784824:ios:4b793e3d7c3169f9874e4d',
    messagingSenderId: '880436784824',
    projectId: 'tools-sharing-f91a6',
    storageBucket: 'tools-sharing-f91a6.appspot.com',
    iosClientId: '880436784824-iqtjtr84lk81aj29l0igdh09d00j897c.apps.googleusercontent.com',
    iosBundleId: 'com.example.manualTools.RunnerTests',
  );
}
