name: tools_sharing
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection: any
  path: any
  intl: any
  my_fatoorah: ^3.4.0-beta.2
  ready_form: ^1.2.4
  ready_validation: ^2.5.0
  mask_text_input_formatter: ^2.4.0
  ready_extensions: ^1.3.0
  firebase_core: ^2.13.0
  cloud_firestore: ^4.7.1
  firebase_auth: ^4.6.1
  dynamic_color: ^1.6.5
  ready_image: ^1.0.0
  firebase_storage: ^11.2.1
  file_picker: ^5.3.2
  url_launcher: ^6.1.11
  maps_launcher: ^2.2.0
  google_sign_in: ^6.1.2
  open_location_picker: ^1.0.2
  flutter_staggered_grid_view: ^0.6.2
  geolocator: ^9.0.2
  shared_preferences: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
dependency_overrides:
  http: ^1.0.0
  win32: ^5.0.2

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
